### ISSUE TITLE
adding support for edu.stanford.nlp.ie.crf.CRFClassifier ?

### ISSUE THREAD

**Issue by behrica** [simongray/datalinguist#5]
I started to work to make the CRFClassifier easy to use from Clojure.

My goal is to "integrate" the classifier in the `tech.ml` library, which has a extension mechanism, so that third parties can contribute models to it:
https://github.com/techascent/tech.ml

And I will use a dataset dataframe to get data in and out.
https://github.com/techascent/tech.ml.dataset

The code is basically done, it's just a few lines of data conversions.

I could contribute it eventually here, instead of making a standalone library.

It has the following dependencies:
edu.stanford.nlp/stanford-corenlp {:mvn/version "4.2.0"}
techascent/tech.ml {:mvn/version "5.01"}
clojurewerkz/propertied {:mvn/version "1.3.0"}

Do you think it could fit here ?

**Comment by simongray** [comment]
This is definitely feeding my impostor syndrome, given that I haven't even packaged and released this library anywhere. I guess this is a pretty good reason for me get on it. 

If the goal is to provide a bridge to a CoreNLP classifier so that it integrates nicely with Clojure and common Clojure libs - which it seems like it is - then I guess it does make sense to place it here. That's really what I'm trying to do myself:

1) make CoreNLP accessible from a REPL
2) integrate with existing libraries/protocols in the Clojure ecosystem

My only caveat would be streamlining the code style/API to make it fit in with the rest of the code, but that's really only because I haven't seen the code you've written. Also, I hope you can live with the fact that CoreNLP - and this library by extension - is released as GPL v3.

**Comment by behrica** [comment]
GPL-3 is not a problem for me.

I can easily make a PR here, so we can discuss the code.
It is a thin wrapper arround edu.stanford.nlp.ie.crf.CRFClassifier,

adapting it to `tech.ml`   predict/train
and tech.v3.dataset  , so it takes its text from a text column of a dataset.

**Comment by behrica** [comment]
Opened PR: #6
